import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, relative } from 'path';
import { parseFrontmatter } from './frontmatter.js';
import { walkMd } from './walk.js';
import { BUILD_INDEX_SKIP } from './constants.js';
import type { Frontmatter } from './frontmatter.js';
import type { WikiContext } from './context.js';

type PageEntry = { file: string; rel: string; fm: Frontmatter };

function row(cells: string[]): string {
  return `| ${cells.join(' | ')} |`;
}

function buildIndexOutput(wikiDir: string): { output: string; pages: PageEntry[] } {
  const pages = walkMd(wikiDir)
    .filter((f) => !BUILD_INDEX_SKIP.some((s) => f.endsWith(s)))
    .map((f) => {
      const content = readFileSync(f, 'utf8');
      const fm = parseFrontmatter(content) ?? {};
      return { file: f, rel: relative(wikiDir, f).replace(/\\/g, '/'), fm };
    })
    .filter((p) => p.fm.type);

  const byType: Record<string, PageEntry[]> = {
    hub: [],
    entity: [],
    concept: [],
    source: [],
  };

  for (const page of pages) {
    if (page.fm.type === 'hub') byType.hub.push(page);
    else if (page.fm.type === 'overview' && page.rel.startsWith('entities/'))
      byType.entity.push(page);
    else if (page.fm.type === 'concept') byType.concept.push(page);
    else if (page.fm.type === 'source') byType.source.push(page);
  }

  for (const bucket of Object.values(byType)) {
    bucket.sort((a, b) =>
      ((a.fm.title as string) ?? '').localeCompare((b.fm.title as string) ?? ''),
    );
  }

  const sections: string[] = [];

  sections.push('## Overview & Hub Pages\n');
  sections.push(row(['Title', 'Status', 'Updated']));
  sections.push(row(['---', '---', '---']));
  if (byType.hub.length === 0) {
    sections.push(row(['_(none yet)_', '', '']));
  } else {
    for (const { rel, fm } of byType.hub) {
      sections.push(
        row([
          `[${fm.title ?? rel}](${rel})`,
          (fm.status as string) ?? '',
          (fm.last_updated as string) ?? '',
        ]),
      );
    }
  }

  sections.push('\n## Entities\n');
  sections.push(row(['Title', 'Scope tag', 'Status', 'Updated']));
  sections.push(row(['---', '---', '---', '---']));
  if (byType.entity.length === 0) {
    sections.push(row(['_(none yet)_', '', '', '']));
  } else {
    for (const { rel, fm } of byType.entity) {
      const tags = Array.isArray(fm.tags) ? fm.tags : [];
      const scopeTag = tags[0] ?? '';
      sections.push(
        row([
          `[${fm.title ?? rel}](${rel})`,
          scopeTag,
          (fm.status as string) ?? '',
          (fm.last_updated as string) ?? '',
        ]),
      );
    }
  }

  sections.push('\n## Concepts\n');
  sections.push(row(['Title', 'Tags', 'Status', 'Updated']));
  sections.push(row(['---', '---', '---', '---']));
  if (byType.concept.length === 0) {
    sections.push(row(['_(none yet)_', '', '', '']));
  } else {
    for (const { rel, fm } of byType.concept) {
      const tags = Array.isArray(fm.tags) ? fm.tags.join(', ') : ((fm.tags as string) ?? '');
      sections.push(
        row([
          `[${fm.title ?? rel}](${rel})`,
          tags,
          (fm.status as string) ?? '',
          (fm.last_updated as string) ?? '',
        ]),
      );
    }
  }

  sections.push('\n## Sources\n');
  sections.push(row(['Title', 'Status', 'Ingested']));
  sections.push(row(['---', '---', '---']));
  if (byType.source.length === 0) {
    sections.push(row(['_(none yet)_', '', '']));
  } else {
    for (const { rel, fm } of byType.source) {
      sections.push(
        row([
          `[${fm.title ?? rel}](${rel})`,
          (fm.status as string) ?? '',
          (fm.last_updated as string) ?? '',
        ]),
      );
    }
  }

  const output = [
    '# Wiki Index',
    '',
    '> Auto-generated by `llm-wiki-manager build`. Do not edit by hand.',
    '',
    '---',
    '',
    ...sections,
    '',
  ].join('\n');

  return { output, pages };
}

// Tolerate CRLF: consumer repos rarely force eol=lf, so git may check
// index.md out with CRLF while the generator produces LF.
function normalizeEol(content: string): string {
  return content.replace(/\r\n/g, '\n');
}

export function isIndexStale(wikiDir: string): boolean {
  const { output } = buildIndexOutput(wikiDir);
  const indexPath = join(wikiDir, 'index.md');
  const existing = existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : '';
  return normalizeEol(existing) !== normalizeEol(output);
}

export function runBuild(ctx: WikiContext): number {
  const { wikiDir } = ctx;
  const { output, pages } = buildIndexOutput(wikiDir);
  const indexPath = join(wikiDir, 'index.md');
  writeFileSync(indexPath, output, 'utf8');
  console.log(`✓ index.md written (${pages.length} page(s))`);
  return 0;
}

export function runCheck(ctx: WikiContext): number {
  const { wikiDir } = ctx;
  const { output, pages } = buildIndexOutput(wikiDir);
  const indexPath = join(wikiDir, 'index.md');
  const existing = existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : '';
  if (normalizeEol(existing) !== normalizeEol(output)) {
    console.error('✗ index.md is stale — run npm run wiki:build');
    return 1;
  }
  console.log(`✓ index.md is up to date (${pages.length} page(s))`);
  return 0;
}
